---
swagger: "2.0"
info:
    description: ""
    version: ""
    title: "Alzheimers IoT API"
paths:
    /memoryGame:
        post:
            tags:
            - ""
            description: ""
            operationId: ""
            parameters:
            -   name: "user"
                in: "body"
                description: "Patient's name"
                required: true
                type: "String"               
            -   name: "score"
                in: "body"
                description: "Patient's score on memory game"
                required: true
                type: "Integer"           
            -   name: "time"
                in: "body"
                description: "Timestamp for when memory game was completed, a ISO 8601 UTC date, e.g.: 1994-11-05T13:15:30Z"
                required: true
                type: "Date"
            responses: 
                200: 
                    description: "Successful response - (MemoryGame entry created!) /
                    /- iff all parameters are entered correctly -- Otherwise, as /
                    / long as you are connected to mongo, you will receive a 200."
                    schema:
                        $ref: " "
                404:
                    description: "Not Found - (Cannot POST)"
                    schema:
                        $ref: " "
    /gps:
        post:
            tags:
            - ""
            descrtiption: ""
            operationID: ""
            parameters:
            -   name: "time"
                in: "body"
                description: "Timestamp of when location was recorded, a ISO 8601 UTC date, e.g.: 1994-11-05T13:15:30Z"
                required: "true"
                type: "Date"
            -   name: "lat"
                in: "body"
                description: "Latitude of location"
                required: "true"
                type: "double"
            -   name: "lon"
                in: "body"
                description: "Longitude of location"
                required: "true"
                type: "double"
            -   name: "address"
                in: "body"
                description: "Address corresponding to longitude and latitude of location"
                required: "true"
                type: "string"
            responses:
                200:
                    description: "At the moment, every response is a successful response - (GPS entry created!)"
                    schema:
                        $ref:
                404:
                    description: 
                    schema:
                        $ref:           
    /wemo:
        post:
            tags:
            - ""
            description: ""
            operationId: ""
            parameters:
            -   name: "date"
                in: "body"
                description: "String representation of the date the entry was made, of the form: (XXXX(year)-XX(month)-XX(day))"
                required: true
                type: "String"
            -   name: "time"
                in: "body"
                description: "String representation of the time the entry was made, of the form: (XX(hours):XX(minutes):XX(seconds))"
                required: true
                type: "String"
            -   name: "status"
                in: "body"
                description: "Boolean value as to whether a device is powered on or off"
                required: true
                type: "Boolean"
            responses: 
                200: 
                    description: "Successful response - ()"
                    schema:
                        $ref: " "
                404:
                    description: "Not Found - (Cannot POST)"
                    schema:
                        $ref: 